version: 2

project_name: vb

before:
  hooks:
    - go mod tidy
    - go run cmd/generate_completions.go
    - go run cmd/generate_man.go

builds:
  # Standard (headless-safe) build — CGO_ENABLED=0, cross-compiles from any runner
  - id: vb
    main: .
    binary: vb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    builds: [vb]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - completions/*
      - man/vb.1
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  extra_files: []

snapshot:
  name_template: "{{ .Tag }}-next"
